server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  #链路监控
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 # 采样率值介于0到1之间，1则表示全部采集

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.2.66:3316/spring_cloud_2020?characterEncoding=utf8&nullCatalogMeansCurrent=true&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.guiyang.springcloud.entities
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群版
      #defaultZone: http://localhost:7001/eureka #单机版
  instance:
    instance-id: payment8001 #服务名称
    prefer-ip-address: true #在eureka界面，鼠标悬停在该服务的status时，页面左下角显示ip
#    #eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
#    lease-renewal-interval-in-seconds: 1
#    #eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除服务
#    lease-expiration-duration-in-seconds: 2
