server:
  port: 8803
spring:
  application:
    name: cloud-stream-consument
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 172.16.2.66
                port: 5672
                username: guest
                password: guest
      bindings:
        input:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit
          group: consumerA
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群版
  instance:
    lease-expiration-duration-in-seconds: 5 # 如果现在超时了5秒的间隔(默认是90秒)
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    instance-id: receive-8803.com # 在信息列表时显示主机名称
    prefer-ip-address: true # 访问的路径变为IP地址