server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com  #需要在C:\Windows\System32\driver\etc\hosts文件中做映射 127.0.0.1 eureka7001.com
  client:
    fetch-registry: false #false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索服务
    register-with-eureka: false #false表示不向注册中心注册自己
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/ #设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址

#  #配置eureka是否进入绝情模式(接受不到服务心跳时，立即删除)
#  server:
#    enable-self-preservation: false #禁用自我保护机制（自我保护:微服务掉线或网络堵塞时，也不会删除该服务信息（好死不如赖活着））
#    eviction-interval-timer-in-ms: 2000