server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #换成nginx的1111端口，做集群
        server-addr: 172.16.2.66:1111
        #        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
