server:
  port: 83
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        #换成nginx的1111端口，做集群
        server-addr: 172.16.2.66:1111
        #        server-addr: localhost:8848

#消费者将要去访问的微服务名称（注册成功通过nacos的服务器提供者)
service-url:
  nacos-user-service: http://nacos-payment-provider